[package]
name = "cpp_rust_str_test"
version = "0.1.0"
edition = "2018"

[lib]
name = "print_floats"
crate-type = ["staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
